name: "Hello"
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  issues: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} (${{ matrix.version }}) for ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: x86_64
            distro: Debian
            version: bullseye
          # - arch: aarch64
          #   distro: Debian
          #   version: bullseye
          # - arch: ppc64le
          #   distro: Debian
          #   version: bullseye
          # - arch: risc64
          #   distro: Ubuntu
          #   version: ubuntu_latest

    id: build
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - run: nix build
      - run: nix flake check
